import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  containerProfile: {
    flex: 1,
    backgroundColor: '#fff'
  },
  containerHome: {
    backgroundColor: "#fff",
    height: "100%",
    backgroundColor: '#eee'
  },
  containerSub: {
    backgroundColor: "#fff",
    height: "100%",
    paddingTop: 60,
  },
  PopupMain: {
    position: "absolute",
    left: "0%",
    zIndex: 9999999,
    width: "100%",
    height: "100%",
    backgroundColor: "rgba(0,0,0,0.5)",
    color: "#fff",
  },
  PopupInner: {
    margin: "15%",
    width: "70%",
    backgroundColor: "#fff",
    padding: 10,
    borderRadius: 10,
    elevation: 5,
    shadowColor: "#000",
  },
  DashboardHeader: {
    elevation: 5,
    shadowColor: "#000",
    backgroundColor: "#fff",
    paddingTop: 40,
    borderBottomEndRadius: 20,
    borderBottomStartRadius: 20,
    borderColor: "#eee",
    borderWidth: 1,
  },
  RecentlyCardBox: {
    elevation: 1,
    shadowColor: "#000",
    backgroundColor: "#fff",
    width: "97%",
    borderRadius: 10,
    padding: 3,
    margin: "1.5%",
    margin: "1%",
  },
  RegisterTop: {
    backgroundColor: "#000",
    height: 180,
    borderBottomEndRadius: 50,
    borderBottomStartRadius: 50,
    justifyContent: "center",
  },
  LoginTop: {
    backgroundColor: "#000",
    height: 200,
    borderBottomEndRadius: 50,
    borderBottomStartRadius: 50,
    justifyContent: "center",
  },
  OtpVerifyHead: {
    textAlign: "center",
    fontSize: 28,
    color: "#000",
    marginTop: 50,
    marginBottom: 10,
  },
  LoginTopText: {
    textAlign: "center",
    fontSize: 28,
    color: "#fff",
    marginTop: 30,
  },
  RegisterTopText: {
    textAlign: "center",
    fontSize: 28,
    color: "#fff",
    marginTop: 30,
  },
  RegisterTopText1: {
    textAlign: "center",
    fontSize: 28,
    color: "#000",
    marginTop: 50,
    marginBottom: 50,
  },
  LoginTopText1: {
    textAlign: "center",
    fontSize: 28,
    color: "#000",
    marginTop: 50,
    marginBottom: 50,
  },
  LoginInput: {
    width: "80%",
    borderWidth: 1,
    borderColor: "#E3E2E2",
    padding: 10,
    paddingLeft: 30,
    margin: 8,
    borderRadius: 50,
    fontSize: 16,
  },
  LoginCheckBoxSection: {
    flexDirection: "row",
    marginTop: 10,
  },
  LoginCheckBoxText: {
    paddingLeft: 10,
    fontSize: 14,
    color: "#777",
  },
  SubBtn: {
    width: 100,
    backgroundColor: "#eee",
    textAlign: "center",
    padding: 12,
    borderRadius: 50,
    fontWeight: 'bold',
    marginTop: 15,
    color: "#000",
    fontSize: 12,
    borderColor: '#ccc',
    borderWidth: 1,
  },

  loginBtn: {
    width: "80%",
    backgroundColor: "#000",
    marginTop: 30,
    textAlign: "center",
    padding: 12,
    borderRadius: 50,
    color: "#fff",
    fontSize: 18,
  },
  loginSocial: {
    color: "#000",
    fontSize: 16,
    alignSelf: 'center',
    alignItems: 'center',
    paddingTop: 2,
  },
  SocialBtn: {
    flexDirection: 'row',
    width: '80%',
    backgroundColor: "#eee",
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 50,
    padding: 10,
    paddingLeft: 30,
    marginTop: 15,
  },
  RegisterBtn: {
    width: "80%",
    backgroundColor: "#000",
    marginTop: 30,
    textAlign: "center",
    padding: 12,
    borderRadius: 50,
    color: "#fff",
    fontSize: 18,
  },
  DashCardList: {
    width: 200,
    height: 150,
    backgroundColor: "#F5F5F5",
    margin: 8,
    textAlign: "center",
    textAlignVertical: "center",
    padding: 10,
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#eee',
    marginBottom: 5,
  },
  SubscriptionImg: {
    width: 400,
    height: 230,
    margin: 8,
    marginBottom: 30,
    textAlign: "center",
    textAlignVertical: "center",
  },
  LiveChalangesList: {
    width: '97%',
    height: 150,
    marginBottom: 0,
  },
  WorkOutVideo: {
    width: '100%',
    height: 220,
    backgroundColor: "#F5F5F5",
    borderRadius: 10,
  },
  BlogImg: {
    width: '100%',
    height: 200,
    backgroundColor: "#F5F5F5",
    borderRadius: 10,
  },
  LiveBox: {
    fontSize: 12,
    backgroundColor: '#ccc',
    marginTop: 6,
    color: '#000',
    flexDirection: 'row',
    verticalAlign: 'middle',
  },
  LiveBox1: {
    paddingLeft: 10,
    fontSize: 12,
    backgroundColor: '#000',
    margin: 10,
    marginTop: 0,
    padding: 5,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    flexDirection: 'row',
    verticalAlign: 'middle',
    height: 40,
  },
  myProgramsList: {
    width: 240,
    height: 180,
    backgroundColor: "#F5F5F5",
    margin: 10,
    textAlign: "center",
    textAlignVertical: "center",
    padding: 10,
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#eee'
  },
  OtherBlog: {
    width: 280,
    height: 160,
    backgroundColor: "#F5F5F5",
    margin: 10,
    textAlign: "center",
    textAlignVertical: "center",
    padding: 10,
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#eee'
  },
  foodLogsList: {
    width: 120,
    height: 120,
    backgroundColor: "#F5F5F5",
    margin: 10,
    textAlign: "center",
    textAlignVertical: "center",
    padding: 10,
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#eee'
  },
  DietGuidelines: {
    width: 100,
    height: 100,
    backgroundColor: "#F5F5F5",
    margin: 10,
    textAlign: "center",
    textAlignVertical: "center",
    padding: 10,
    borderRadius: 10,
    color: "#fff",
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#eee'
  },
  ProfileHeader: {
    flexDirection: 'row',
    backgroundColor: "#fff",
    height: 50,
    marginTop: 32,
    padding: 12,
    textAlign: 'center'
  },
  ProfileHeadText: {
    fontSize: 20,
    alignSelf: 'center'
  },
  ProductBtn1: {
    width: "96%",
    marginStart: "2%",
    elevation: 1,
    shadowColor: "#000",
    margin: "2%",
    marginTop: "0%",
    borderRadius: 15,
    paddingBottom: 20,
    backgroundColor: "#fff",
    padding: 8,
    borderColor: "#E0E0E0",
    borderWidth: 1
  },
  AddToCart: {
    backgroundColor: '#000',
    width: 100,
    textAlign: 'center',
    padding: 5,
    margin: 5,
    color: 'white',
    borderRadius: 10
  },
  AddToCart1: {
    backgroundColor: '#000',
    width: 30,
    textAlign: 'center',
    padding: 5,
    margin: 5,
    color: 'white',
    borderRadius: 10
  },
  AddToQty: {
    backgroundColor: '#f6e7ff',
    width: 30,
    textAlign: 'center',
    padding: 5,
    margin: 5,
    color: 'white',
    borderRadius: 10,
    color: '#000'
  },
  OverViewData: {
    flex: 4,
    width: 200,
    margin: 12,
    flexWrap: 'wrap',
    alignItems: 'center'
  },
  OverTitle: {
    width: '100%',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 2
  },
  OverDisc: {
    width: '100%',
    marginBottom: 15,
    fontSize: 16
  },
  CaloriCard: {
    backgroundColor: '#f7f7f7',
    borderWidth: 1,
    borderColor: '#eee',
    padding: 5,
    marginTop: 10,
    marginBottom: 5,
    borderRadius: 10,
    elevation: 1
  },
  CaloriCardDasHome: {
    backgroundColor: '#eee',
    padding: 10,
    marginBottom: 10,
    borderRadius: 10,
    width: 330,
    margin: 5,
    minHeight: 200,
  },
  CalSearchInput: {
    fontSize: 10,
    width: '100%',
  },
  addCalTitle: {
    fontSize: 12,
    color: '#777'
  },
  addCalDis: {
    fontSize: 14,
    marginBottom: 5
  },
  AddCalImg: {
    width: 60,
    height: 60,
    backgroundColor: '#ccc',
    margin: 10,
    borderRadius: 50,
  },
  ProfileUpInput: {
    borderColor: '#eee',
    height: 50,
    borderWidth: 1,
    paddingLeft: 15,
    paddingRight: 15,
    borderRadius: 5,
    marginBottom: 15,
    fontSize: 18,
  },
  ProfileUpBtn: {
    backgroundColor: '#000',
    height: 50,
    color: '#fff',
    padding: 10,
    borderRadius: 50,
    marginTop: 40,
    fontSize: 18,
    textAlign: 'center'
  },
  PackageBox: {
    backgroundColor: '#fff',
    width: 280,
    minHeight: 130,
    margin: 10,
    marginTop: 30,
    padding: 10,
    marginBottom: 30,
    borderRadius: 10,
    borderColor: '#ccc',
    borderWidth: 1,
  },
  centeredView: {
    flex: 1,
    //justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
  },
  modalView: {
    margin: 0,
    width: '98%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 10,
    //alignItems: 'center',
    // shadowColor: '#000',
    // shadowOpacity: 0.25,
    // shadowRadius: 4,
    // elevation: 5,
  },
  popClose: {
    color: '#000',
    backgroundColor: '#ccc',
    padding: 10,
    width: 100,
    textAlign: 'center',
    marginTop: '20%',
    borderRadius: 25,
  },
  QtySubmit: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 10,
    marginTop: 10,
    borderRadius: 5,

  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  AddFoodBox: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: "#e3e3e3",
    padding: 5,
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 7,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  AddFoodBox1: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: "#e3e3e3",
    padding: 5,
    borderRadius: 10,
    paddingLeft: 10,
    paddingRight: 10,
    marginTop: 7,
    width: 320,
    // justifyContent: 'center',
    // alignItems: 'center',
  },
  video: {
    width: "100%",
    height: "100%",
    margin: 0,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
  },
  ProgramThums: {
    textAlign: "center",
    fontSize: 20,
    fontWeight: "bold",
    padding: 2,
    // backgroundColor: '#f7f7f7',
    marginTop: 10,
    marginRight: 15,
    paddingRight: 6,
    paddingLeft: 6,
    borderRadius: 10,
    // borderWidth: 1,
    borderColor: '#ccc',
  },
  MainQuestionBox: {
    padding: 10,
    width: '96%',
    margin: '2%',
    marginTop: 3,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 5,
    elevation: 2,
  },
  Question: {
    fontSize: 16,
  },
  Answer: {
    padding: 10,
    borderWidth: 1,
    borderColor: '#eee',
    borderRadius: 5,
    marginTop: 10,
  },
  dropdownButtonStyle: {
    width: 200,
    height: 50,
    backgroundColor: '#E9ECEF',
    borderRadius: 12,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  dropdownButtonTxtStyle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '500',
    color: '#151E26',
  },
  dropdownButtonArrowStyle: {
    fontSize: 28,
  },
  dropdownButtonIconStyle: {
    fontSize: 28,
    marginRight: 8,
  },
  dropdownMenuStyle: {
    backgroundColor: '#E9ECEF',
    borderRadius: 8,
  },
  dropdownItemStyle: {
    width: '100%',
    flexDirection: 'row',
    paddingHorizontal: 12,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 8,
  },
  dropdownItemTxtStyle: {
    flex: 1,
    fontSize: 18,
    fontWeight: '500',
    color: '#151E26',
  },
  dropdownItemIconStyle: {
    fontSize: 28,
    marginRight: 8,
  },
});



export default styles;
